<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE dataset [
  <!ELEMENT dataset (table)*>
  <!ELEMENT table (column|row)*>
  <!ATTLIST table
    name CDATA #REQUIRED>
  <!ELEMENT column (#PCDATA)>
  <!ELEMENT row (value)*>
  <!ELEMENT value (#PCDATA)>
  ]>
<!--
    PLEASE PAY ATTENTION IF YOU ADD MORE RECORDS!
    In some tests (ie copy tests) we "cheat" and we check new records directly using the new ID, to simplify testing.
    For example, if I know that there are 5 records, I know that the next one will have ID = 6.
    If you add more rows, you'll likely get some problems, so please remember to double check tests.
-->
<dataset>
  <table name="jos_foftest_foobars">
    <column>foftest_foobar_id</column>
    <column>title</column>
    <column>slug</column>
    <column>enabled</column>
    <column>ordering</column>
    <column>hits</column>
    <column>asset_id</column>
    <column>access</column>
    <column>created_by</column>
    <column>created_on</column>
    <column>modified_by</column>
    <column>modified_on</column>
    <column>locked_by</column>
    <column>locked_on</column>
    <row>
      <value>1</value>
      <value>Guinea Pig row</value>
      <value>guinea-pig-row</value>
      <value>1</value>
      <value>1</value>
      <value>0</value>
      <value>0</value>
      <value>2</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>2</value>
      <value>Second row</value>
      <value>second-row</value>
      <value>0</value>
      <value>2</value>
      <value>23</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>3</value>
      <value>Third row</value>
      <value>third-row</value>
      <value>1</value>
      <value>3</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>4</value>
      <value>Fourth row</value>
      <value>fourth-row</value>
      <value>0</value>
      <value>4</value>
      <value>0</value>
      <value>54</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>5</value>
      <value>Locked record</value>
      <value>locked-record</value>
      <value>1</value>
      <value>5</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>99</value>
      <value>2013-06-24 13:00:00</value>
    </row>
  </table>

  <table name="jos_foftest_foobaraliases">
    <column>id_foobar_aliases</column>
    <column>fo_title</column>
    <column>fo_slug</column>
    <column>fo_enabled</column>
    <column>fo_ordering</column>
    <column>fo_hits</column>
    <column>fo_asset_id</column>
    <column>fo_access</column>
    <column>fo_created_by</column>
    <column>fo_created_on</column>
    <column>fo_modified_by</column>
    <column>fo_modified_on</column>
    <column>fo_locked_by</column>
    <column>fo_locked_on</column>
    <row>
      <value>1</value>
      <value>Aliased Guinea Pig row</value>
      <value>aliased-guinea-pig-row</value>
      <value>1</value>
      <value>1</value>
      <value>0</value>
      <value>0</value>
      <value>2</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>2</value>
      <value>Second row</value>
      <value>second-row</value>
      <value>0</value>
      <value>2</value>
      <value>12</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>3</value>
      <value>Third row</value>
      <value>third-row</value>
      <value>1</value>
      <value>3</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>4</value>
      <value>Fourth row</value>
      <value>fourth-row</value>
      <value>0</value>
      <value>4</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>5</value>
      <value>Locked record</value>
      <value>locked-record</value>
      <value>1</value>
      <value>5</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>99</value>
      <value>2013-06-24 13:00:00</value>
    </row>
  </table>

  <table name="jos_foftest_bares">
    <column>foftest_bare_id</column>
    <column>title</column>
    <row>
      <value>1</value>
      <value>First Row</value>
    </row>
    <row>
      <value>2</value>
      <value>Second Row</value>
    </row>
    <row>
      <value>3</value>
      <value>Third Row</value>
    </row>
  </table>

  <table name="jos_foftest_foobarjoins">
    <column>foftest_id_foobarjoin</column>
    <column>external_key</column>
    <column>fj_title</column>
    <column>fj_dummy</column>
    <column>title</column>
    <row>
      <value>1</value>
      <value>2</value>
      <value>First row unique colum name</value>
      <value>Dummy value for row 1</value>
      <value>First row non-unique colum name</value>
    </row>
    <row>
      <value>2</value>
      <value>4</value>
      <value>Second row unique colum name</value>
      <value>Dummy value for row 2</value>
      <value>Second row non-unique colum name</value>
    </row>
  </table>

  <table name="jos_fakeapp_parents">
    <column>fakeapp_parent_id</column>
    <column>dummy</column>

    <row>
      <value>1</value>
      <value>First parent row</value>
    </row>

    <row>
      <value>2</value>
      <value>Second parent row</value>
    </row>

    <row>
      <value>3</value>
      <value>Parent with no children</value>
    </row>
  </table>

  <table name="jos_fakeapp_children">
    <column>fakeapp_child_id</column>
    <column>dummy</column>
    <column>fakeapp_parent_id</column>

    <row>
      <value>1</value>
      <value>Parent 1 - First children</value>
      <value>1</value>
    </row>

    <row>
      <value>2</value>
      <value>Parent 1 - Second children</value>
      <value>1</value>
    </row>

    <row>
      <value>3</value>
      <value>Parent 2 - First children</value>
      <value>2</value>
    </row>
  </table>

  <table name="jos_fakeapp_parts">
    <column>fakeapp_part_id</column>
    <column>description</column>

    <row>
      <value>1</value>
      <value>Part number 1</value>
    </row>
    <row>
      <value>2</value>
      <value>Part number 2</value>
    </row>
    <row>
      <value>3</value>
      <value>Part number 3</value>
    </row>
  </table>

  <table name="jos_fakeapp_groups">
    <column>fakeapp_group_id</column>
    <column>description</column>

    <row>
      <value>1</value>
      <value>Group number 1</value>
    </row>
    <row>
      <value>2</value>
      <value>Group number 2</value>
    </row>
    <row>
      <value>3</value>
      <value>Group number 3</value>
    </row>
  </table>

  <table name="jos_fakeapp_parts_groups">
    <column>fakeapp_group_id</column>
    <column>fakeapp_part_id</column>

    <row>
      <value>1</value>
      <value>1</value>
    </row>
    <row>
      <value>1</value>
      <value>2</value>
    </row>
    <row>
      <value>1</value>
      <value>3</value>
    </row>
    <row>
      <value>2</value>
      <value>1</value>
    </row>
    <row>
      <value>2</value>
      <value>2</value>
    </row>
  </table>

  <table name="jos_foftest_joomlachildren">
    <column>foftest_joomlachild_id</column>
    <column>dummy</column>
    <column>user_id</column>

    <row>
      <value>1</value>
      <value>First row, first FOF test user</value>
      <value>998</value>
    </row>

    <row>
      <value>2</value>
      <value>Second row, first FOF test user</value>
      <value>998</value>
    </row>

    <row>
      <value>3</value>
      <value>Third row, second FOF test user</value>
      <value>999</value>
    </row>
  </table>

  <table name="jos_foftest_nestedsets">
    <column>foftest_nestedset_id</column>
    <column>title</column>
    <column>slug</column>
    <column>lft</column>
    <column>rgt</column>
    <column>hash</column>

    <row>
      <value>1</value>
      <value>ROOT</value>
      <value>root</value>
      <value>1</value>
      <value>32</value>
      <value>dc76e9f0c0006e8f919e0c515c66dbba3982f785</value>
    </row>

    <row>
      <value>2</value>
      <value>Electronics</value>
      <value>electronics</value>
      <value>2</value>
      <value>15</value>
      <value>1ed41f53f6e46bae8c539f14baf2af7e80028245</value>
    </row>

    <row>
      <value>3</value>
      <value>Audio</value>
      <value>audio</value>
      <value>3</value>
      <value>4</value>
      <value>a06a492959ce12b3f0292406ec84177d07ae19b1</value>
    </row>

    <row>
      <value>4</value>
      <value>Imaging</value>
      <value>imaging</value>
      <value>5</value>
      <value>14</value>
      <value>c6e642e2b148af42898b69133e7e718d0769d41a</value>
    </row>

    <row>
      <value>5</value>
      <value>Photography</value>
      <value>photography</value>
      <value>6</value>
      <value>11</value>
      <value>9aa15b5bf5c702f55fd8263ecb4f690854aadabd</value>
    </row>

    <row>
      <value>6</value>
      <value>Compact</value>
      <value>compact</value>
      <value>7</value>
      <value>8</value>
      <value>4f44e2cffa8f7b516c9e499285c951d788431a28</value>
    </row>

    <row>
      <value>7</value>
      <value>DSLR</value>
      <value>dslr</value>
      <value>9</value>
      <value>10</value>
      <value>fb199bb4d6e6036068150a832a2d0624da6e32c6</value>
    </row>

    <row>
      <value>8</value>
      <value>Video</value>
      <value>video</value>
      <value>12</value>
      <value>13</value>
      <value>ffbaf58f1231628f9ac2a583f038b51719006ec6</value>
    </row>

    <row>
      <value>9</value>
      <value>Computers</value>
      <value>computers</value>
      <value>16</value>
      <value>31</value>
      <value>dd708279cb3a8477c9ddb927e917a8087a0de08c</value>
    </row>

    <row>
      <value>10</value>
      <value>Smartphones</value>
      <value>smartphones</value>
      <value>17</value>
      <value>22</value>
      <value>c2c34a12a4f0f8bc8ad689d2738026d8d507686f</value>
    </row>

    <row>
      <value>11</value>
      <value>Apple</value>
      <value>apple</value>
      <value>18</value>
      <value>19</value>
      <value>d0be2dc421be4fcd0172e5afceea3970e2f3d940</value>
    </row>

    <row>
      <value>12</value>
      <value>Android</value>
      <value>android</value>
      <value>20</value>
      <value>21</value>
      <value>e4bbe5b7a4c1eb55652965aee885dd59bd2ee7f4</value>
    </row>

    <row>
      <value>13</value>
      <value>Laptops</value>
      <value>laptops</value>
      <value>23</value>
      <value>24</value>
      <value>3de877ddfb06db510e63893d98ddac9524696c14</value>
    </row>

    <row>
      <value>14</value>
      <value>Tablets</value>
      <value>tablets</value>
      <value>25</value>
      <value>30</value>
      <value>d67b0e1caa50e6d14951e33fd2b334969d09edf0</value>
    </row>

    <row>
      <value>15</value>
      <value>Apple</value>
      <value>apple-1</value>
      <value>26</value>
      <value>27</value>
      <value>12be6773ef3b5b87b850912c28bc2debb49d77ea</value>
    </row>

    <row>
      <value>16</value>
      <value>Android</value>
      <value>android</value>
      <value>28</value>
      <value>29</value>
      <value>e4bbe5b7a4c1eb55652965aee885dd59bd2ee7f4</value>
    </row>
  </table>

  <table name="jos_foftest_lockedon">
    <column>id</column>
    <column>locked_on</column>

    <row>
      <value>1</value>
      <value>0000-00-00 00:00:00</value>
    </row>
  </table>

  <!-- Restore the assets table, so we can play with them -->
  <table name="jos_assets">
    <column>id</column>
    <column>parent_id</column>
    <column>lft</column>
    <column>rgt</column>
    <column>level</column>
    <column>name</column>
    <column>title</column>
    <column>rules</column>

    <row>
      <value>1</value>
      <value>0</value>
      <value>0</value>
      <value>105</value>
      <value>0</value>
      <value>root.1</value>
      <value>Root Asset</value>
      <value>{&quot;core.login.site&quot;:{&quot;6&quot;:1,&quot;2&quot;:1},&quot;core.login.admin&quot;:{&quot;6&quot;:1},&quot;core.login.offline&quot;:{&quot;6&quot;:1},&quot;core.admin&quot;:{&quot;8&quot;:1},&quot;core.manage&quot;:{&quot;7&quot;:1},&quot;core.create&quot;:{&quot;6&quot;:1,&quot;3&quot;:1},&quot;core.delete&quot;:{&quot;6&quot;:1},&quot;core.edit&quot;:{&quot;6&quot;:1,&quot;4&quot;:1},&quot;core.edit.state&quot;:{&quot;6&quot;:1,&quot;5&quot;:1},&quot;core.edit.own&quot;:{&quot;6&quot;:1,&quot;3&quot;:1}}</value>
    </row>

    <row>
      <value>2</value>
      <value>1</value>
      <value>1</value>
      <value>2</value>
      <value>1</value>
      <value>com_admin</value>
      <value>com_admin</value>
      <value>{}</value>
    </row>

    <row>
      <value>3</value>
      <value>1</value>
      <value>3</value>
      <value>6</value>
      <value>1</value>
      <value>com_banners</value>
      <value>com_banners</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>4</value>
      <value>1</value>
      <value>7</value>
      <value>8</value>
      <value>1</value>
      <value>com_cache</value>
      <value>com_cache</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;7&quot;:1}}</value>
    </row>

    <row>
      <value>5</value>
      <value>1</value>
      <value>9</value>
      <value>10</value>
      <value>1</value>
      <value>com_checkin</value>
      <value>com_checkin</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;7&quot;:1}}</value>
    </row>

    <row>
      <value>6</value>
      <value>1</value>
      <value>11</value>
      <value>12</value>
      <value>1</value>
      <value>com_config</value>
      <value>com_config</value>
      <value>{}</value>
    </row>

    <row>
      <value>7</value>
      <value>1</value>
      <value>13</value>
      <value>16</value>
      <value>1</value>
      <value>com_contact</value>
      <value>com_contact</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>8</value>
      <value>1</value>
      <value>17</value>
      <value>20</value>
      <value>1</value>
      <value>com_content</value>
      <value>com_content</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:{&quot;3&quot;:1},&quot;core.delete&quot;:[],&quot;core.edit&quot;:{&quot;4&quot;:1},&quot;core.edit.state&quot;:{&quot;5&quot;:1},&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>9</value>
      <value>1</value>
      <value>21</value>
      <value>22</value>
      <value>1</value>
      <value>com_cpanel</value>
      <value>com_cpanel</value>
      <value>{}</value>
    </row>

    <row>
      <value>10</value>
      <value>1</value>
      <value>23</value>
      <value>24</value>
      <value>1</value>
      <value>com_installer</value>
      <value>com_installer</value>
      <value>{&quot;core.admin&quot;:[],&quot;core.manage&quot;:{&quot;7&quot;:0},&quot;core.delete&quot;:{&quot;7&quot;:0},&quot;core.edit.state&quot;:{&quot;7&quot;:0}}</value>
    </row>

    <row>
      <value>11</value>
      <value>1</value>
      <value>25</value>
      <value>26</value>
      <value>1</value>
      <value>com_languages</value>
      <value>com_languages</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>12</value>
      <value>1</value>
      <value>27</value>
      <value>28</value>
      <value>1</value>
      <value>com_login</value>
      <value>com_login</value>
      <value>{}</value>
    </row>

    <row>
      <value>13</value>
      <value>1</value>
      <value>29</value>
      <value>30</value>
      <value>1</value>
      <value>com_mailto</value>
      <value>com_mailto</value>
      <value>{}</value>
    </row>

    <row>
      <value>14</value>
      <value>1</value>
      <value>31</value>
      <value>32</value>
      <value>1</value>
      <value>com_massmail</value>
      <value>com_massmail</value>
      <value>{}</value>
    </row>

    <row>
      <value>15</value>
      <value>1</value>
      <value>33</value>
      <value>34</value>
      <value>1</value>
      <value>com_media</value>
      <value>com_media</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:{&quot;3&quot;:1},&quot;core.delete&quot;:{&quot;5&quot;:1}}</value>
    </row>

    <row>
      <value>16</value>
      <value>1</value>
      <value>35</value>
      <value>36</value>
      <value>1</value>
      <value>com_menus</value>
      <value>com_menus</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>17</value>
      <value>1</value>
      <value>37</value>
      <value>38</value>
      <value>1</value>
      <value>com_messages</value>
      <value>com_messages</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;7&quot;:1}}</value>
    </row>

    <row>
      <value>18</value>
      <value>1</value>
      <value>39</value>
      <value>70</value>
      <value>1</value>
      <value>com_modules</value>
      <value>com_modules</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>19</value>
      <value>1</value>
      <value>71</value>
      <value>74</value>
      <value>1</value>
      <value>com_newsfeeds</value>
      <value>com_newsfeeds</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>20</value>
      <value>1</value>
      <value>75</value>
      <value>76</value>
      <value>1</value>
      <value>com_plugins</value>
      <value>com_plugins</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>21</value>
      <value>1</value>
      <value>77</value>
      <value>78</value>
      <value>1</value>
      <value>com_redirect</value>
      <value>com_redirect</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[]}</value>
    </row>

    <row>
      <value>22</value>
      <value>1</value>
      <value>79</value>
      <value>80</value>
      <value>1</value>
      <value>com_search</value>
      <value>com_search</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1}}</value>
    </row>

    <row>
      <value>23</value>
      <value>1</value>
      <value>81</value>
      <value>82</value>
      <value>1</value>
      <value>com_templates</value>
      <value>com_templates</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>24</value>
      <value>1</value>
      <value>83</value>
      <value>86</value>
      <value>1</value>
      <value>com_users</value>
      <value>com_users</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>25</value>
      <value>1</value>
      <value>87</value>
      <value>90</value>
      <value>1</value>
      <value>com_weblinks</value>
      <value>com_weblinks</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:{&quot;3&quot;:1},&quot;core.delete&quot;:[],&quot;core.edit&quot;:{&quot;4&quot;:1},&quot;core.edit.state&quot;:{&quot;5&quot;:1},&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>26</value>
      <value>1</value>
      <value>91</value>
      <value>92</value>
      <value>1</value>
      <value>com_wrapper</value>
      <value>com_wrapper</value>
      <value>{}</value>
    </row>

    <row>
      <value>27</value>
      <value>8</value>
      <value>18</value>
      <value>19</value>
      <value>2</value>
      <value>com_content.category.2</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>28</value>
      <value>3</value>
      <value>4</value>
      <value>5</value>
      <value>2</value>
      <value>com_banners.category.3</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>29</value>
      <value>7</value>
      <value>14</value>
      <value>15</value>
      <value>2</value>
      <value>com_contact.category.4</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>30</value>
      <value>19</value>
      <value>72</value>
      <value>73</value>
      <value>2</value>
      <value>com_newsfeeds.category.5</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>31</value>
      <value>25</value>
      <value>88</value>
      <value>89</value>
      <value>2</value>
      <value>com_weblinks.category.6</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>32</value>
      <value>24</value>
      <value>84</value>
      <value>85</value>
      <value>1</value>
      <value>com_users.category.7</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>33</value>
      <value>1</value>
      <value>93</value>
      <value>94</value>
      <value>1</value>
      <value>com_finder</value>
      <value>com_finder</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1}}</value>
    </row>

    <row>
      <value>34</value>
      <value>1</value>
      <value>95</value>
      <value>96</value>
      <value>1</value>
      <value>com_joomlaupdate</value>
      <value>com_joomlaupdate</value>
      <value>{&quot;core.admin&quot;:[],&quot;core.manage&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>35</value>
      <value>1</value>
      <value>97</value>
      <value>98</value>
      <value>1</value>
      <value>com_tags</value>
      <value>com_tags</value>
      <value>{&quot;core.admin&quot;:[],&quot;core.manage&quot;:[],&quot;core.manage&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>36</value>
      <value>1</value>
      <value>99</value>
      <value>100</value>
      <value>1</value>
      <value>com_contenthistory</value>
      <value>com_contenthistory</value>
      <value>{}</value>
    </row>

    <row>
      <value>37</value>
      <value>1</value>
      <value>101</value>
      <value>102</value>
      <value>1</value>
      <value>com_ajax</value>
      <value>com_ajax</value>
      <value>{}</value>
    </row>

    <row>
      <value>38</value>
      <value>1</value>
      <value>103</value>
      <value>104</value>
      <value>1</value>
      <value>com_postinstall</value>
      <value>com_postinstall</value>
      <value>{}</value>
    </row>

    <row>
      <value>39</value>
      <value>18</value>
      <value>40</value>
      <value>41</value>
      <value>2</value>
      <value>com_modules.module.1</value>
      <value>Main Menu</value>
      <value>{&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>40</value>
      <value>18</value>
      <value>42</value>
      <value>43</value>
      <value>2</value>
      <value>com_modules.module.2</value>
      <value>Login</value>
      <value>{&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>41</value>
      <value>18</value>
      <value>44</value>
      <value>45</value>
      <value>2</value>
      <value>com_modules.module.3</value>
      <value>Popular Articles</value>
      <value>{&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>42</value>
      <value>18</value>
      <value>46</value>
      <value>47</value>
      <value>2</value>
      <value>com_modules.module.4</value>
      <value>Recently Added Articles</value>
      <value>{&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>43</value>
      <value>18</value>
      <value>48</value>
      <value>49</value>
      <value>2</value>
      <value>com_modules.module.8</value>
      <value>Toolbar</value>
      <value>{&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>44</value>
      <value>18</value>
      <value>50</value>
      <value>51</value>
      <value>2</value>
      <value>com_modules.module.9</value>
      <value>Quick Icons</value>
      <value>{&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>45</value>
      <value>18</value>
      <value>52</value>
      <value>53</value>
      <value>2</value>
      <value>com_modules.module.10</value>
      <value>Logged-in Users</value>
      <value>{&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>46</value>
      <value>18</value>
      <value>54</value>
      <value>55</value>
      <value>2</value>
      <value>com_modules.module.12</value>
      <value>Admin Menu</value>
      <value>{&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>47</value>
      <value>18</value>
      <value>56</value>
      <value>57</value>
      <value>2</value>
      <value>com_modules.module.13</value>
      <value>Admin Submenu</value>
      <value>{&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>48</value>
      <value>18</value>
      <value>58</value>
      <value>59</value>
      <value>2</value>
      <value>com_modules.module.14</value>
      <value>User Status</value>