<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE dataset [
  <!ELEMENT dataset (table)*>
  <!ELEMENT table (column|row)*>
  <!ATTLIST table
    name CDATA #REQUIRED>
  <!ELEMENT column (#PCDATA)>
  <!ELEMENT row (value)*>
  <!ELEMENT value (#PCDATA)>
  ]>
<!--
    PLEASE PAY ATTENTION IF YOU ADD MORE RECORDS!
    In some tests (ie copy tests) we "cheat" and we check new records directly using the new ID, to simplify testing.
    For example, if I know that there are 5 records, I know that the next one will have ID = 6.
    If you add more rows, you'll likely get some problems, so please remember to double check tests.
-->
<dataset>
  <table name="jos_foftest_foobars">
    <column>foftest_foobar_id</column>
    <column>title</column>
    <column>slug</column>
    <column>enabled</column>
    <column>ordering</column>
    <column>hits</column>
    <column>asset_id</column>
    <column>access</column>
    <column>created_by</column>
    <column>created_on</column>
    <column>modified_by</column>
    <column>modified_on</column>
    <column>locked_by</column>
    <column>locked_on</column>
    <row>
      <value>1</value>
      <value>Guinea Pig row</value>
      <value>guinea-pig-row</value>
      <value>1</value>
      <value>1</value>
      <value>0</value>
      <value>0</value>
      <value>2</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>2</value>
      <value>Second row</value>
      <value>second-row</value>
      <value>0</value>
      <value>2</value>
      <value>23</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>3</value>
      <value>Third row</value>
      <value>third-row</value>
      <value>1</value>
      <value>3</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>4</value>
      <value>Fourth row</value>
      <value>fourth-row</value>
      <value>0</value>
      <value>4</value>
      <value>0</value>
      <value>54</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>5</value>
      <value>Locked record</value>
      <value>locked-record</value>
      <value>1</value>
      <value>5</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>99</value>
      <value>2013-06-24 13:00:00</value>
    </row>
  </table>

  <table name="jos_foftest_foobaraliases">
    <column>id_foobar_aliases</column>
    <column>fo_title</column>
    <column>fo_slug</column>
    <column>fo_enabled</column>
    <column>fo_ordering</column>
    <column>fo_hits</column>
    <column>fo_asset_id</column>
    <column>fo_access</column>
    <column>fo_created_by</column>
    <column>fo_created_on</column>
    <column>fo_modified_by</column>
    <column>fo_modified_on</column>
    <column>fo_locked_by</column>
    <column>fo_locked_on</column>
    <row>
      <value>1</value>
      <value>Aliased Guinea Pig row</value>
      <value>aliased-guinea-pig-row</value>
      <value>1</value>
      <value>1</value>
      <value>0</value>
      <value>0</value>
      <value>2</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>2</value>
      <value>Second row</value>
      <value>second-row</value>
      <value>0</value>
      <value>2</value>
      <value>12</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>3</value>
      <value>Third row</value>
      <value>third-row</value>
      <value>1</value>
      <value>3</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>4</value>
      <value>Fourth row</value>
      <value>fourth-row</value>
      <value>0</value>
      <value>4</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
    </row>
    <row>
      <value>5</value>
      <value>Locked record</value>
      <value>locked-record</value>
      <value>1</value>
      <value>5</value>
      <value>0</value>
      <value>0</value>
      <value>1</value>
      <value>42</value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value>0000-00-00 00:00:00</value>
      <value>99</value>
      <value>2013-06-24 13:00:00</value>
    </row>
  </table>

  <table name="jos_foftest_bares">
      <column>foftest_bare_id</column>
      <column>title</column>
      <row>
          <value>1</value>
          <value>First Row</value>
      </row>
      <row>
          <value>2</value>
          <value>Second Row</value>
      </row>
      <row>
          <value>3</value>
          <value>Third Row</value>
      </row>
  </table>

  <table name="jos_foftest_foobarjoins">
      <column>foftest_id_foobarjoin</column>
      <column>external_key</column>
      <column>fj_title</column>
      <column>fj_dummy</column>
      <column>title</column>
      <row>
          <value>1</value>
          <value>2</value>
          <value>First row unique colum name</value>
          <value>Dummy value for row 1</value>
          <value>First row non-unique colum name</value>
      </row>
      <row>
          <value>2</value>
          <value>4</value>
          <value>Second row unique colum name</value>
          <value>Dummy value for row 2</value>
          <value>Second row non-unique colum name</value>
      </row>
  </table>

  <table name="jos_foftest_parents">
    <column>foftest_parent_id</column>
    <column>dummy</column>

    <row>
      <value>1</value>
      <value>First parent row</value>
    </row>

    <row>
      <value>2</value>
      <value>Second parent row</value>
    </row>

    <row>
      <value>3</value>
      <value>Parent with no children</value>
    </row>
  </table>

  <table name="jos_foftest_children">
    <column>foftest_child_id</column>
    <column>dummy</column>
    <column>foftest_parent_id</column>

    <row>
      <value>1</value>
      <value>Parent 1 - First children</value>
      <value>1</value>
    </row>

    <row>
      <value>2</value>
      <value>Parent 1 - Second children</value>
      <value>1</value>
    </row>

    <row>
      <value>3</value>
      <value>Parent 2 - First children</value>
      <value>2</value>
    </row>
  </table>

  <table name="jos_foftest_parts">
    <column>foftest_part_id</column>
    <column>dummy</column>

    <row>
      <value>1</value>
      <value>Part number 1</value>
    </row>
    <row>
      <value>2</value>
      <value>Part number 2</value>
    </row>
    <row>
      <value>3</value>
      <value>Part number 3</value>
    </row>
  </table>

  <table name="jos_foftest_groups">
    <column>foftest_group_id</column>
    <column>dummy</column>

    <row>
      <value>1</value>
      <value>Group number 1</value>
    </row>
    <row>
      <value>2</value>
      <value>Group number 2</value>
    </row>
    <row>
      <value>3</value>
      <value>Group number 3</value>
    </row>
  </table>

  <table name="jos_foftest_parts_groups">
    <column>foftest_group_id</column>
    <column>foftest_part_id</column>

    <row>
      <value>1</value>
      <value>1</value>
    </row>
    <row>
      <value>1</value>
      <value>2</value>
    </row>
    <row>
      <value>1</value>
      <value>3</value>
    </row>
    <row>
      <value>2</value>
      <value>1</value>
    </row>
    <row>
      <value>2</value>
      <value>2</value>
    </row>
  </table>

  <table name="jos_foftest_joomlachildren">
    <column>foftest_joomlachild_id</column>
    <column>dummy</column>
    <column>user_id</column>

    <row>
      <value>1</value>
      <value>First row, first FOF test user</value>
      <value>998</value>
    </row>

    <row>
      <value>2</value>
      <value>Second row, first FOF test user</value>
      <value>998</value>
    </row>

    <row>
      <value>3</value>
      <value>Third row, second FOF test user</value>
      <value>999</value>
    </row>
  </table>

  <table name="jos_foftest_nestedsets">
    <column>foftest_nestedset_id</column>
    <column>title</column>
    <column>slug</column>
    <column>lft</column>
    <column>rgt</column>
    <column>hash</column>

    <row>
      <value>1</value>
      <value>ROOT</value>
      <value>root</value>
      <value>1</value>
      <value>32</value>
      <value>77e7e78b05578758626744dcdf57007c71797399</value>
    </row>

    <row>
      <value>2</value>
      <value>Electronics</value>
      <value>electronics</value>
      <value>2</value>
      <value>15</value>
      <value>89f1ebf5ace10fe4d43c85a7ad419905164b9883</value>
    </row>

    <row>
      <value>3</value>
      <value>Audio</value>
      <value>audio</value>
      <value>3</value>
      <value>4</value>
      <value>acdac205f5e24cb75113c4b281a2c13f08b75159</value>
    </row>

    <row>
      <value>4</value>
      <value>Imaging</value>
      <value>imaging</value>
      <value>5</value>
      <value>14</value>
      <value>731feee62c52c112d615a7851cd03f2cf5ed0794</value>
    </row>

    <row>
      <value>5</value>
      <value>Photography</value>
      <value>photography</value>
      <value>6</value>
      <value>11</value>
      <value>b987e3f155a21c976430d228badd3fcf156bbeb2</value>
    </row>

    <row>
      <value>6</value>
      <value>Compact</value>
      <value>compact</value>
      <value>7</value>
      <value>8</value>
      <value>1df39aa58ad4033d56b836b47d7830d400029d70</value>
    </row>

    <row>
      <value>7</value>
      <value>DSLR</value>
      <value>dslr</value>
      <value>9</value>
      <value>10</value>
      <value>ccf5f51bcde86b4c4b8af749948d133351463bab</value>
    </row>

    <row>
      <value>8</value>
      <value>Video</value>
      <value>video</value>
      <value>12</value>
      <value>13</value>
      <value>bc17c1f0179a888f2a7e8389f67d4f2cf5cf4531</value>
    </row>

    <row>
      <value>9</value>
      <value>Computers</value>
      <value>computers</value>
      <value>16</value>
      <value>31</value>
      <value>62d3cc0d94efd1c3ff52b19f67c74f0b058a4d64</value>
    </row>

    <row>
      <value>10</value>
      <value>Smartphones</value>
      <value>smartphones</value>
      <value>17</value>
      <value>22</value>
      <value>42be68579ce19ac3c57bf8d3ff11bfdd465bbe85</value>
    </row>

    <row>
      <value>11</value>
      <value>Apple</value>
      <value>apple</value>
      <value>18</value>
      <value>19</value>
      <value>476432a3e85a0aa21c23f5abd2975a89b6820d63</value>
    </row>

    <row>
      <value>12</value>
      <value>Android</value>
      <value>android</value>
      <value>20</value>
      <value>21</value>
      <value>1928f95c598b9e69462fcb512625cf8e28923044</value>
    </row>

    <row>
      <value>13</value>
      <value>Laptops</value>
      <value>laptops</value>
      <value>23</value>
      <value>24</value>
      <value>8632c32a7b0a4b8b0c3856f9af2f93ff486719d2</value>
    </row>

    <row>
      <value>14</value>
      <value>Tablets</value>
      <value>tablets</value>
      <value>25</value>
      <value>30</value>
      <value>e75fe50d9415216b8c0140cb9fc6b1f30474ba33</value>
    </row>

    <row>
      <value>15</value>
      <value>Apple</value>
      <value>apple</value>
      <value>26</value>
      <value>27</value>
      <value>476432a3e85a0aa21c23f5abd2975a89b6820d63</value>
    </row>

    <row>
      <value>16</value>
      <value>Android</value>
      <value>android</value>
      <value>28</value>
      <value>29</value>
      <value>1928f95c598b9e69462fcb512625cf8e28923044</value>
    </row>


  </table>

  <table name="jos_session">
    <column>session_id</column>
    <column>client_id</column>
    <column>guest</column>
    <column>time</column>
    <column>data</column>
    <column>userid</column>
    <column>username</column>
    <row>
        <value>r2qg13f3kae3oq88quf834gf70</value>
        <value>0</value>
        <value>0</value>
        <value>1372346276</value>
        <value>__default|a:8:{s:15:"session.counter";i:1;s:19:"session.timer.start";i:1372346275;s:18:"session.timer.last";i:1372346275;s:17:"session.timer.now";i:1372346275;s:22:"session.client.browser";s:72:"Mozilla/5.0 (Windows NT 6.1; WOW64; rv:21.0) Gecko/20100101 Firefox/21.0";s:8:"registry";O:9:"JRegistry":1:{s:7:"\\0\\0\\0data";O:8:"stdClass":0:{}}s:4:"user";O:5:"JUser":24:{s:9:"\\0\\0\\0isRoot";b:0;s:2:"id";i:0;s:4:"name";N;s:8:"username";N;s:5:"email";N;s:8:"password";N;s:14:"password_clear";s:0:"";s:5:"block";N;s:9:"sendEmail";i:0;s:12:"registerDate";N;s:13:"lastvisitDate";N;s:10:"activation";N;s:6:"params";N;s:6:"groups";a:1:{i:0;s:1:"9";}s:5:"guest";i:1;s:13:"lastResetTime";N;s:10:"resetCount";N;s:10:"\\0\\0\\0_params";O:9:"JRegistry":1:{s:7:"\\0\\0\\0data";O:8:"stdClass":0:{}}s:14:"\\0\\0\\0_authGroups";a:2:{i:0;i:1;i:1;i:9;}s:14:"\\0\\0\\0_authLevels";a:3:{i:0;i:1;i:1;i:1;i:2;i:5;}s:15:"\\0\\0\\0_authActions";N;s:12:"\\0\\0\\0_errorMsg";N;s:10:"\\0\\0\\0_errors";a:0:{}s:3:"aid";i:0;}s:13:"session.token";s:32:"ce1f6e2722f22e7f26a40ded25e87100";}</value>
        <value>99</value>
        <value>FakeUser</value>
    </row>
  </table>

  <!-- The password for all users is "foftest" -->
  <table name="jos_users">
    <column>id</column>
    <column>name</column>
    <column>username</column>
    <column>email</column>
    <column>password</column>
    <column>block</column>
    <column>sendEmail</column>
    <column>registerDate</column>
    <column>lastvisitDate</column>
    <column>activation</column>
    <column>params</column>
    <column>lastResetTime</column>
    <column>resetCount</column>
    <column>otpKey</column>
    <column>otep</column>

    <row>
      <value>37</value>
      <value>Super User</value>
      <value>admin</value>
      <value>admin@example.com</value>
      <value>0127d5044a06dfb33a4e299537a6a629</value>
      <value>0</value>
      <value>1</value>
      <value>2014-03-10 08:57:19</value>
      <value>2014-03-10 08:57:34</value>
      <value>0</value>
      <value></value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value></value>
      <value></value>
    </row>

    <row>
      <value>998</value>
      <value>FOFTest user 1</value>
      <value>foftest1</value>
      <value>foftest1@example.com</value>
      <value>0127d5044a06dfb33a4e299537a6a629</value>
      <value>0</value>
      <value>1</value>
      <value>2014-03-10 08:57:19</value>
      <value>2014-03-10 08:57:34</value>
      <value>0</value>
      <value></value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value></value>
      <value></value>
    </row>

    <row>
      <value>999</value>
      <value>FOFTest user 2</value>
      <value>foftest2</value>
      <value>foftest2@example.com</value>
      <value>0127d5044a06dfb33a4e299537a6a629</value>
      <value>0</value>
      <value>1</value>
      <value>2014-03-10 08:57:19</value>
      <value>2014-03-10 08:57:34</value>
      <value>0</value>
      <value></value>
      <value>0000-00-00 00:00:00</value>
      <value>0</value>
      <value></value>
      <value></value>
    </row>
  </table>

  <table name="jos_user_usergroup_map">
    <column>user_id</column>
    <column>group_id</column>

    <row>
      <value>37</value>
      <value>8</value>
    </row>

    <row>
      <value>998</value>
      <value>8</value>
    </row>

    <row>
      <value>999</value>
      <value>8</value>
    </row>
  </table>

  <!-- Restore the assets table, so we can play with them -->
  <table name="jos_assets">
    <column>id</column>
    <column>parent_id</column>
    <column>lft</column>
    <column>rgt</column>
    <column>level</column>
    <column>name</column>
    <column>title</column>
    <column>rules</column>

    <row>
      <value>1</value>
      <value>0</value>
      <value>0</value>
      <value>105</value>
      <value>0</value>
      <value>root.1</value>
      <value>Root Asset</value>
      <value>{&quot;core.login.site&quot;:{&quot;6&quot;:1,&quot;2&quot;:1},&quot;core.login.admin&quot;:{&quot;6&quot;:1},&quot;core.login.offline&quot;:{&quot;6&quot;:1},&quot;core.admin&quot;:{&quot;8&quot;:1},&quot;core.manage&quot;:{&quot;7&quot;:1},&quot;core.create&quot;:{&quot;6&quot;:1,&quot;3&quot;:1},&quot;core.delete&quot;:{&quot;6&quot;:1},&quot;core.edit&quot;:{&quot;6&quot;:1,&quot;4&quot;:1},&quot;core.edit.state&quot;:{&quot;6&quot;:1,&quot;5&quot;:1},&quot;core.edit.own&quot;:{&quot;6&quot;:1,&quot;3&quot;:1}}</value>
    </row>

    <row>
      <value>2</value>
      <value>1</value>
      <value>1</value>
      <value>2</value>
      <value>1</value>
      <value>com_admin</value>
      <value>com_admin</value>
      <value>{}</value>
    </row>

    <row>
      <value>3</value>
      <value>1</value>
      <value>3</value>
      <value>6</value>
      <value>1</value>
      <value>com_banners</value>
      <value>com_banners</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>4</value>
      <value>1</value>
      <value>7</value>
      <value>8</value>
      <value>1</value>
      <value>com_cache</value>
      <value>com_cache</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;7&quot;:1}}</value>
    </row>

    <row>
      <value>5</value>
      <value>1</value>
      <value>9</value>
      <value>10</value>
      <value>1</value>
      <value>com_checkin</value>
      <value>com_checkin</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;7&quot;:1}}</value>
    </row>

    <row>
      <value>6</value>
      <value>1</value>
      <value>11</value>
      <value>12</value>
      <value>1</value>
      <value>com_config</value>
      <value>com_config</value>
      <value>{}</value>
    </row>

    <row>
      <value>7</value>
      <value>1</value>
      <value>13</value>
      <value>16</value>
      <value>1</value>
      <value>com_contact</value>
      <value>com_contact</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>8</value>
      <value>1</value>
      <value>17</value>
      <value>20</value>
      <value>1</value>
      <value>com_content</value>
      <value>com_content</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:{&quot;3&quot;:1},&quot;core.delete&quot;:[],&quot;core.edit&quot;:{&quot;4&quot;:1},&quot;core.edit.state&quot;:{&quot;5&quot;:1},&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>9</value>
      <value>1</value>
      <value>21</value>
      <value>22</value>
      <value>1</value>
      <value>com_cpanel</value>
      <value>com_cpanel</value>
      <value>{}</value>
    </row>

    <row>
      <value>10</value>
      <value>1</value>
      <value>23</value>
      <value>24</value>
      <value>1</value>
      <value>com_installer</value>
      <value>com_installer</value>
      <value>{&quot;core.admin&quot;:[],&quot;core.manage&quot;:{&quot;7&quot;:0},&quot;core.delete&quot;:{&quot;7&quot;:0},&quot;core.edit.state&quot;:{&quot;7&quot;:0}}</value>
    </row>

    <row>
      <value>11</value>
      <value>1</value>
      <value>25</value>
      <value>26</value>
      <value>1</value>
      <value>com_languages</value>
      <value>com_languages</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>12</value>
      <value>1</value>
      <value>27</value>
      <value>28</value>
      <value>1</value>
      <value>com_login</value>
      <value>com_login</value>
      <value>{}</value>
    </row>

    <row>
      <value>13</value>
      <value>1</value>
      <value>29</value>
      <value>30</value>
      <value>1</value>
      <value>com_mailto</value>
      <value>com_mailto</value>
      <value>{}</value>
    </row>

    <row>
      <value>14</value>
      <value>1</value>
      <value>31</value>
      <value>32</value>
      <value>1</value>
      <value>com_massmail</value>
      <value>com_massmail</value>
      <value>{}</value>
    </row>

    <row>
      <value>15</value>
      <value>1</value>
      <value>33</value>
      <value>34</value>
      <value>1</value>
      <value>com_media</value>
      <value>com_media</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:{&quot;3&quot;:1},&quot;core.delete&quot;:{&quot;5&quot;:1}}</value>
    </row>

    <row>
      <value>16</value>
      <value>1</value>
      <value>35</value>
      <value>36</value>
      <value>1</value>
      <value>com_menus</value>
      <value>com_menus</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>17</value>
      <value>1</value>
      <value>37</value>
      <value>38</value>
      <value>1</value>
      <value>com_messages</value>
      <value>com_messages</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;7&quot;:1}}</value>
    </row>

    <row>
      <value>18</value>
      <value>1</value>
      <value>39</value>
      <value>70</value>
      <value>1</value>
      <value>com_modules</value>
      <value>com_modules</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>19</value>
      <value>1</value>
      <value>71</value>
      <value>74</value>
      <value>1</value>
      <value>com_newsfeeds</value>
      <value>com_newsfeeds</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>20</value>
      <value>1</value>
      <value>75</value>
      <value>76</value>
      <value>1</value>
      <value>com_plugins</value>
      <value>com_plugins</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>21</value>
      <value>1</value>
      <value>77</value>
      <value>78</value>
      <value>1</value>
      <value>com_redirect</value>
      <value>com_redirect</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[]}</value>
    </row>

    <row>
      <value>22</value>
      <value>1</value>
      <value>79</value>
      <value>80</value>
      <value>1</value>
      <value>com_search</value>
      <value>com_search</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1}}</value>
    </row>

    <row>
      <value>23</value>
      <value>1</value>
      <value>81</value>
      <value>82</value>
      <value>1</value>
      <value>com_templates</value>
      <value>com_templates</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>24</value>
      <value>1</value>
      <value>83</value>
      <value>86</value>
      <value>1</value>
      <value>com_users</value>
      <value>com_users</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:[],&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>25</value>
      <value>1</value>
      <value>87</value>
      <value>90</value>
      <value>1</value>
      <value>com_weblinks</value>
      <value>com_weblinks</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1},&quot;core.create&quot;:{&quot;3&quot;:1},&quot;core.delete&quot;:[],&quot;core.edit&quot;:{&quot;4&quot;:1},&quot;core.edit.state&quot;:{&quot;5&quot;:1},&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>26</value>
      <value>1</value>
      <value>91</value>
      <value>92</value>
      <value>1</value>
      <value>com_wrapper</value>
      <value>com_wrapper</value>
      <value>{}</value>
    </row>

    <row>
      <value>27</value>
      <value>8</value>
      <value>18</value>
      <value>19</value>
      <value>2</value>
      <value>com_content.category.2</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>28</value>
      <value>3</value>
      <value>4</value>
      <value>5</value>
      <value>2</value>
      <value>com_banners.category.3</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>29</value>
      <value>7</value>
      <value>14</value>
      <value>15</value>
      <value>2</value>
      <value>com_contact.category.4</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>30</value>
      <value>19</value>
      <value>72</value>
      <value>73</value>
      <value>2</value>
      <value>com_newsfeeds.category.5</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>31</value>
      <value>25</value>
      <value>88</value>
      <value>89</value>
      <value>2</value>
      <value>com_weblinks.category.6</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[],&quot;core.edit.own&quot;:[]}</value>
    </row>

    <row>
      <value>32</value>
      <value>24</value>
      <value>84</value>
      <value>85</value>
      <value>1</value>
      <value>com_users.category.7</value>
      <value>Uncategorised</value>
      <value>{&quot;core.create&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>33</value>
      <value>1</value>
      <value>93</value>
      <value>94</value>
      <value>1</value>
      <value>com_finder</value>
      <value>com_finder</value>
      <value>{&quot;core.admin&quot;:{&quot;7&quot;:1},&quot;core.manage&quot;:{&quot;6&quot;:1}}</value>
    </row>

    <row>
      <value>34</value>
      <value>1</value>
      <value>95</value>
      <value>96</value>
      <value>1</value>
      <value>com_joomlaupdate</value>
      <value>com_joomlaupdate</value>
      <value>{&quot;core.admin&quot;:[],&quot;core.manage&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>35</value>
      <value>1</value>
      <value>97</value>
      <value>98</value>
      <value>1</value>
      <value>com_tags</value>
      <value>com_tags</value>
      <value>{&quot;core.admin&quot;:[],&quot;core.manage&quot;:[],&quot;core.manage&quot;:[],&quot;core.delete&quot;:[],&quot;core.edit.state&quot;:[]}</value>
    </row>

    <row>
      <value>36</value>
      <value>1</value>
      <value>99</value>
      <value>100</value>